import { PERMISSIONS } from "../permissions/permissions.js";

const rolePermissions = Object.freeze({
  owner: [
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_USAGE,
    PERMISSIONS.VIEW_OWN_USAGE,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_API_KEYS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.SEARCH_DOCUMENTS,
    PERMISSIONS.SEND_EMAIL,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.MANAGE_DOCUMENTS,
  ],
  admin: [
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_USAGE,
    PERMISSIONS.VIEW_OWN_USAGE,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_API_KEYS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.SEARCH_DOCUMENTS,
    PERMISSIONS.SEND_EMAIL,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.MANAGE_DOCUMENTS,
  ],
  member: [
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_OWN_USAGE,
    PERMISSIONS.SEARCH_DOCUMENTS,
  ],
  viewer: [PERMISSIONS.VIEW_USAGE],
});

export class RoleService {
  getPermissions(role) {
    return [...(rolePermissions[role] ?? [])];
  }

  hasPermission(role, permission) {
    return this.getPermissions(role).includes(permission);
  }
}
